### ISSUE TITLE
Command palette support

### ISSUE THREAD

**Issue by Cyanide4Dinner** [Cyanide4Dinner/ravana#12]
Support command palette, which will appear on the bottom and will be used for entering commands vim-style via `:`.

### Requirements 
- Commands will trigger events.
- Proper error handling and response to use on palette itself like vim.
- Customizable shortcuts for triggering commands.
- Rendered user input on each key press.

### Tasks
- [x] Design system model.
- [x] Implement
  - [x] Implement storing and parsing user command.
  - [x] Implement TUI.
  - [x] Implement event trigger. 
- [x] Bugs
