### ISSUE TITLE
Multiple pages support 

### ISSUE THREAD

**Issue by Cyanide4Dinner** [Cyanide4Dinner/ravana#9]
### Requirements
- Multiple pages.
- API to switch between them.
- API to change order.
- API to choose a page as "focused" and that page will be rendered.
- API to change "focused" page.

### Tasks
- [x] Plan modifications needed to support requirements.
- [x] Implement structure modifications.
  - [x] App to track focused page.
  - [x] Focus page.
  - [x] PageBar
    - [x] Sync with App.
    - [x] TUI render.
